"""Analysis/plotting layer for the ``error_model_comparison_18_4_4`` report notebook.

The notebook (generated by ``experiments/methods/make_error_model_comparison.py``) is a
thin sequence of markdown + one-line calls into this module: all loading, estimators,
tables and figures live here so the notebook stays readable. Data comes from the
per-task JSON cache written by ``experiments/methods/run_error_model_comparison.py``
under ``runs/error_model_comparison_18_4_4/`` — no method here runs stim or a decoder;
the only computation is cheap analysis (binomial reweighting of stored spectra,
crossings, error propagation), so the notebook re-executes in seconds.

One method per notebook cell, named in section order. Cells must run in order: later
sections read state stored by earlier ones (e.g. ``fig_budget()`` needs
``budget_table()``'s rows; everything in §7+ needs the §2/§7 loaders).
"""
import json

import numpy as np
import matplotlib.pyplot as plt

from repo_paths import run_dir
from importance_sampling import (FailureSpectrum, reweight_spectrum,
                                 failure_spectrum_ansatz, fit_failure_spectrum,
                                 logical_error_rate_from_ansatz)

TINY = 1e-300           # floors the logs in crossings (deep-sub-onset ε72 can underflow)

COLORS = {"full symmetric": "crimson", "CZ only": "navy", "meas only": "seagreen",
          "prep only": "darkorange", "gate idle": "purple", "meas idle": "mediumvioletred"}

SECTIONS = [("setup + §0 schedule",      ["setup", "schedule"]),
            ("§1 distances/onsets",      ["tech2"]),
            ("§2 spectra (Technique I)", ["tech1"]),
            ("§3 splitting",             ["tech3"]),
            ("§4 direct MC",             ["mc"]),
            ("§5 ablations (18)",        ["tech2_abl", "tech1_abl", "mc_abl"]),
            ("§7 [[72,4,8]] sweeps",     ["tech2_72", "tech1_72", "mc72"]),
            ("§7.5 72-code ablations",   ["tech1_72_abl"]),
            ("§8 asymmetric point",      ["asym"])]


def slug(name):
    return name.replace(" ", "_")


def per_round(LER, rounds):
    return 1.0 - (1.0 - np.clip(LER, 0.0, 1.0 - 1e-12)) ** (1.0 / rounds)


def crossing_p(pg, y1, y2):          # p where y1(p)=y2(p), log-log interpolated (None if never)
    r = np.log(y1) - np.log(y2)
    s = np.nonzero(np.diff(np.sign(r)) != 0)[0]
    if s.size == 0:
        return None
    i = s[-1]; t = r[i] / (r[i] - r[i + 1])
    return float(np.exp(np.log(pg[i]) + t * (np.log(pg[i + 1]) - np.log(pg[i]))))


def pseudo_threshold(pg, LER):       # break-even LER(p)=p (single-code threshold stand-in)
    return crossing_p(pg, LER, np.asarray(pg))


def fill_spectrum(spec):
    """Stride fix (needed before reweighting strided spectra curve-wide).

    ``reweight_spectrum`` sums only SAMPLED weights, so any weight the sweep skipped
    contributes zero — at high p (where binomial mass sits inside the strided tail) the
    raw sum undercounts LER by ~2x at stride 2, and worse at coarser strides. This
    inserts every missing weight between consecutive sampled bins, each carrying the
    POOLED counts of its two bracketing bins, restoring the full mass.

    Generalized 2026-08-03 from a hardcoded stride-2 rule (``W[i+1] == w + 2``) to
    arbitrary gaps, so sweeps can stride hard through the saturated tail where f(w) is
    flat (measured: 0.91-0.96 across w=40..166 on the [[72,4,8]] full-symmetric model).
    Backward compatible: for a gap of 2 it inserts exactly one weight with the same
    pooled counts as before, so cached stride-2 spectra reweight bit-identically.

    Pooling is deliberately MODEL-FREE. Filling from the fitted f5 ansatz instead would
    be circular — the ansatz is fitted to this spectrum, is identically zero below its
    w0, and the sub-onset decoder floor is by definition measured mass the ansatz cannot
    represent. Fill where f varies slowly; do not stride through the onset shoulder.
    """
    W, T, F = list(spec.weights), list(spec.trials), list(spec.failures)
    w_out, t_out, f_out = [], [], []
    for i, (w, t, f) in enumerate(zip(W, T, F)):
        w_out.append(w); t_out.append(t); f_out.append(f)
        if i + 1 < len(W):
            for w_missing in range(w + 1, W[i + 1]):
                w_out.append(w_missing)
                t_out.append(t + T[i + 1])
                f_out.append(f + F[i + 1])
    return FailureSpectrum(weights=w_out, trials=t_out, failures=f_out,
                           n_expanded=spec.n_expanded, q_base=spec.q_base, p_ref=spec.p_ref)


class Report:
    """The report notebook's state: cached-run loaders, estimators, tables, figures."""

    def __init__(self, run_name="error_model_comparison_18_4_4"):
        self.RESULTS = run_dir(run_name)
        MAN = self.load("config__manifest")
        CFG = self.load_meta("config__manifest")["config"]
        self.P_REF, self.ROUNDS, self.ROUNDS72 = CFG["p_ref"], CFG["rounds"], CFG["rounds72"]
        self.p_grid = np.geomspace(CFG["p_grid"]["lo"], CFG["p_grid"]["hi"], CFG["p_grid"]["n"])
        self.MODELS, self.ABLATED, self.CHANNELS = MAN["models"], MAN["ablated"], MAN["channels"]
        self.ABL_OF = dict(zip(self.CHANNELS, self.ABLATED))   # "CZ only" -> "no CZ", ...
        self.P_STAR, self.P_LAM, self.R_OF = MAN["p_star"], MAN["p_lam"], MAN["r_of"]
        self.COLORS = COLORS
        # runner timing: every task file records its wall time
        self.TIMES = {f.stem: {k: json.loads(f.read_text(encoding="utf-8"))[k]
                               for k in ("elapsed_s", "finished_at")}
                      for f in sorted(self.RESULTS.glob("*.json"))}

    # --- cache access ---------------------------------------------------------------

    def load_meta(self, name):
        return json.loads((self.RESULTS / f"{name}.json").read_text(encoding="utf-8"))

    def load(self, name):
        return self.load_meta(name)["result"]

    @staticmethod
    def spectrum_of(r):                   # rebuild the measured spectrum from its JSON fields
        keep = set(FailureSpectrum.__dataclass_fields__)   # drop non-constructor metadata
        return FailureSpectrum(**{k: v for k, v in r["spectrum"].items() if k in keep})

    def section_time(self, *groups):
        ms = [v for k, v in self.TIMES.items() if k.split("__")[0] in groups]
        if not ms:
            return "⏱ runner: no cached tasks found for this section"
        tot = sum(m["elapsed_s"] for m in ms)
        return (f"⏱ runner: {tot:,.0f} s wall over {len(ms)} tasks "
                f"(newest {max(m['finished_at'] for m in ms)})")

    # --- estimators shared by the sections --------------------------------------------

    def rw_stats(self, spec, p):
        """Reweighted-measured-spectrum LER at scalar p: (value, statistical SE, zero-bin headroom).

        SE propagates the per-bin binomial errors of the sampled f(w). `headroom` is how much
        the value could RISE if every sampled-but-zero-failure bin actually sat at its
        rule-of-three upper bound f(w) < 3/T(w). EVERY zero bin is priced, including those
        below tech2's D: D is the PERFECT-decoder floor, but the actual decoder miscorrects
        (returns a wrong-coset correction heavier than the fault) at rates the spectra measure
        directly — e.g. f(1) > 0 on the full 18-code mix — so an empty low-w bin is unresolved
        statistics, not a structural zero.
        """
        v = reweight_spectrum(spec, [p])
        up = FailureSpectrum(weights=spec.weights, trials=spec.trials,
                             failures=[f if f > 0 else min(3, t)
                                       for f, t in zip(spec.failures, spec.trials)],
                             n_expanded=spec.n_expanded, q_base=spec.q_base, p_ref=spec.p_ref)
        head = float(reweight_spectrum(up, [p]).P_logical[0]) - float(v.P_logical[0])
        return float(v.P_logical[0]), float(v.P_logical_se[0]), head

    def eps_stats(self, spec, p, rounds):
        """Per-round ε at p with SE and zero-bin headroom (delta method through 1-(1-L)^{1/r})."""
        L, se, head = self.rw_stats(spec, p)
        g = (1.0 - min(L, 1.0 - 1e-12)) ** (1.0 / rounds - 1.0) / rounds
        return float(per_round(np.asarray([L]), rounds)[0]), g * se, g * head

    def inv_lambda_stats(self, spec18, spec72, p):
        """1/Λ = ε72/ε18 at p: (value, SE, low, high) — low/high span the zero-bin truncation."""
        e18, s18, h18 = self.eps_stats(spec18, p, self.ROUNDS)
        e72, s72, h72 = self.eps_stats(spec72, p, self.ROUNDS72)
        inv = e72 / e18
        se = inv * float(np.hypot(s18 / e18, s72 / e72))
        return inv, se, e72 / (e18 + h18), (e72 + h72) / e18

    # --- setup ------------------------------------------------------------------------

    def dem_counts(self):
        dem = self.load("setup__dem_counts")
        for name in self.MODELS:
            print(f"{name:16s}: {dem[name]} DEM mechanisms")

    def runner_times(self):
        """How long each section's simulations took in the runner (cached wall time, sequential)."""
        print(f"{'section':28s} {'tasks':>5} {'wall time':>12}   newest result")
        grand = 0.0
        for label, groups in SECTIONS:
            ms = [v for k, v in self.TIMES.items() if k.split("__")[0] in groups]
            tot = sum(m["elapsed_s"] for m in ms); grand += tot
            newest = max((m["finished_at"] for m in ms), default="—")
            print(f"{label:28s} {len(ms):5d} {tot:11,.1f}s   {newest}")
        print(f"{'TOTAL':28s} {'':5s} {grand:11,.1f}s   (§6 is pure analysis — no runner tasks)")

    # --- §0 schedule ------------------------------------------------------------------

    def schedule_table(self):
        print(self.load("schedule__table")["table"])
        print()
        print(self.section_time("setup", "schedule"))

    def schedule_svg(self):
        """The noisy one-cycle schedule as a stim timeline-svg, sliced to a closed 7-qubit star.

        Every noise box is tagged and colored by CHANNEL (stim itself labels noise only with
        its probability — all three DEPOLARIZE1 channels would look identical): cz / meas /
        prep / g-idle / m-idle / 1q (post-H 1q-gate noise, not a budget channel). All boxes
        are p=0.01. TWO syndrome cycles are shown because the data m-idle slot only exists
        BETWEEN rounds; the g-idle box is the lone DEP box on the data rail during its sat-out
        CX layer, right after prep. Caveats: ancilla rails show only their coupling to the
        watched data qubit (other CXs are cropped), and rails are renumbered 0..6 — the
        mapping back is printed here.
        """
        from IPython.display import SVG, display
        star = self.load("schedule__star_svg")
        print("rails: " + "   ".join(f"q{new} = {lbl}" for new, old, lbl in star["rails"]))
        print("noise tags: " + "   ".join(f"{t} = {c}" for t, c in star["channel_colors"].items()))
        display(SVG(star["svg"]))

    # --- §1 Technique II ----------------------------------------------------------------

    def tech2_table(self):
        self.tech2 = {name: self.load(f"tech2__{slug(name)}") for name in self.MODELS}
        print(f"{'model':16s} {'D':>2} {'w0':>3} {'#DEM':>6} {'|L(D)|':>8} {'f0*':>8}   route")
        for name in self.MODELS:
            t = self.tech2[name]
            print(f"{name:16s} {t['D']:2d} {t['w0']:3d} {t['n_dem']:6d} {t['n_LD']:8d} "
                  f"{t['f0']:8.4f}   {t['route']}")
        print()
        print(self.section_time("tech2"))

    # --- §2 Technique I -----------------------------------------------------------------

    def load_spectra(self):
        self.tech1 = {}
        for name in self.MODELS:
            r = self.load(f"tech1__{slug(name)}")
            self.tech1[name] = dict(spec=self.spectrum_of(r), LER=np.asarray(r["LER_fit"]),
                                    cost=r["fit"]["cost"], W=r["W"])
            print(f"{name:16s}: w=1..{r['W'][-1]}, measured f(2)={self.tech1[name]['spec'].f(2):.4f} "
                  f"({r['shots']} shots total)   f5 fit cost={r['fit']['cost']:.2f}")
        print()
        print(self.section_time("tech1"))

    # --- §3 Technique III ---------------------------------------------------------------

    def load_splitting(self):
        self.tech3 = {}
        for name in self.MODELS:
            r = self.load(f"tech3__{slug(name)}")
            self.tech3[name] = dict(sp=np.asarray(r["sp"]), sP=np.asarray(r["sP"]))
            print(f"{name:16s}: swap-accept {r['swap_min']:.2f}..{r['swap_max']:.2f}   "
                  f"P(1e-4)={r['sP'][0]:.2e}")
        print()
        print(self.section_time("tech3"))

    # --- §4 direct MC + overlay ---------------------------------------------------------

    def mc_overlay(self):
        self.mc = {name: {float(p): v for p, v in self.load(f"mc__{slug(name)}")["points"].items()}
                   for name in self.MODELS}
        mc_pts = sorted(next(iter(self.mc.values())))
        print("   p        " + "".join(f"{n:>15}" for n in self.MODELS))
        for p in sorted(mc_pts, reverse=True):
            print(f"  {p:.3f}   " + "".join(f"{self.mc[n][p][0]:>15.3e}" for n in self.MODELS))
        print()
        print(self.section_time("mc"))

        fig, ax = plt.subplots(figsize=(9, 6))
        for name in self.MODELS:
            col = self.COLORS[name]
            ax.plot(self.p_grid, self.tech1[name]["LER"], "-", color=col, lw=2, label=f"{name}")
            ax.plot(self.tech3[name]["sp"], self.tech3[name]["sP"], "s", color=col, ms=4, mfc="none")
            ax.errorbar(mc_pts, [self.mc[name][p][0] for p in mc_pts],
                        yerr=[self.mc[name][p][1] for p in mc_pts],
                        fmt="o", color=col, capsize=3, zorder=5)
        ax.plot([], [], "-", color="gray", label="Technique I: f5 ansatz")
        ax.plot([], [], "s", color="gray", mfc="none", label="Technique III: splitting")
        ax.plot([], [], "o", color="gray", label="direct Monte-Carlo")
        ax.set_xscale("log"); ax.set_yscale("log")
        ax.set_xlabel("physical error rate p"); ax.set_ylabel("logical error rate")
        ax.set_title("Kunlun [[18,4,4]] — error-model comparison (three techniques + direct MC)")
        ax.legend(fontsize=8); ax.grid(alpha=0.3, which="both")
        plt.tight_layout(); plt.show()

    # --- §5 ablations -------------------------------------------------------------------

    def tech2_abl_table(self):
        self.tech2_abl = {name: self.load(f"tech2_abl__{slug(name)}") for name in self.ABLATED}
        print(f"{'model':13s} {'D':>2} {'w0':>3} {'#DEM':>6} {'|L(D)|':>8} {'f0*':>10}   hook diagnosis")
        for name in self.ABLATED:
            t = self.tech2_abl[name]
            diag = ("restores D=4 -> channel is in EVERY weight-3 hook" if t["D"] == 4
                    else "still D=3 -> hooks survive without this channel" if t["D"] == 3 else "")
            print(f"{name:13s} {t['D']:2d} {t['w0']:3d} {t['n_dem']:6d} {t['n_LD']:8d} "
                  f"{t['f0']:10.3e}   {diag}")

    def load_ablations(self):
        self.tech1_abl, self.mc_abl = {}, {}
        for name in self.ABLATED:
            r = self.load(f"tech1_abl__{slug(name)}")
            self.tech1_abl[name] = dict(spec=self.spectrum_of(r), LER=np.asarray(r["LER_fit"]),
                                        cost=r["fit"]["cost"])
            self.mc_abl[name] = {float(p): v
                                 for p, v in self.load(f"mc_abl__{slug(name)}")["points"].items()}
            print(f"{name:13s}: f5 fit cost={r['fit']['cost']:.2f}   "
                  f"MC LER(p={min(self.mc_abl[name])}) = "
                  f"{self.mc_abl[name][min(self.mc_abl[name])][0]:.3e}")
        print()
        print(self.section_time("tech2_abl", "tech1_abl", "mc_abl"))

    # --- §6 the budget ------------------------------------------------------------------

    def ler_at(self, d, p):              # reweighted measured spectrum at scalar p (no extrapolation)
        return float(reweight_spectrum(d["spec"], [p]).P_logical[0])

    def split_at(self, name, p):         # Technique-III splitting estimate at p (log-log interpolated)
        sp, sP = self.tech3[name]["sp"], self.tech3[name]["sP"]
        return float(np.exp(np.interp(np.log(p), np.log(sp), np.log(sP))))

    def budget_table(self):
        P_STAR, p_grid = self.P_STAR, self.p_grid
        self.L_full, L_full_se, _ = self.rw_stats(self.tech1["full symmetric"]["spec"], P_STAR)
        L_full = self.L_full
        S_full = self.split_at("full symmetric", P_STAR)
        rows = []
        for ch in self.CHANNELS:
            iso = self.ler_at(self.tech1[ch], P_STAR) / L_full
            La, La_se, _ = self.rw_stats(self.tech1_abl[self.ABL_OF[ch]]["spec"], P_STAR)
            marg = 1.0 - La / L_full
            marg_se = (La / L_full) * float(np.hypot(La_se / La, L_full_se / L_full))
            iso_split = self.split_at(ch, P_STAR) / S_full
            pth = pseudo_threshold(p_grid, self.tech1[ch]["LER"])
            rows.append((ch, iso, marg, iso_split, pth, marg_se))
        self.rows6 = rows

        print(f"error budget at p* = {P_STAR}   (LER_full: reweighted {L_full:.3e}, "
              f"splitting {S_full:.3e})")
        print(f"{'channel':12s} {'isolated':>9} {'iso(split)':>10} {'marginal':>9} {'±σ':>6} "
              f"{'p_pth':>9} {'p*/p_pth':>9}")
        for ch, iso, marg, iso_split, pth, mse in rows:
            pths = f"{pth:.4f}" if pth else f">{p_grid.max():.3g}"    # no break-even crossing in-grid
            term = f"{P_STAR/pth:.3f}" if pth else f"<{P_STAR/p_grid.max():.3f}"  # bound, not a blank
            print(f"{ch:12s} {iso:9.3f} {iso_split:10.3f} {marg:9.3f} {mse:6.3f} {pths:>9} {term:>9}")
        self.mixing = 1.0 - sum(r[1] for r in rows)
        spam_iso = sum(r[1] for r in rows if r[0] in ("meas only", "prep only"))
        spam_marg = sum(r[2] for r in rows if r[0] in ("meas only", "prep only"))
        idle_iso = sum(r[1] for r in rows if "idle" in r[0])
        idle_marg = sum(r[2] for r in rows if "idle" in r[0])
        print(f"{'mixing':12s} {self.mixing:9.3f}                             "
              f"(1 - sum isolated: cross-channel faults)")
        print(f"{'SPAM':12s} {spam_iso:9.3f} {'':10s} {spam_marg:9.3f}         (meas + prep combined)")
        print(f"{'idle total':12s} {idle_iso:9.3f} {'':10s} {idle_marg:9.3f}         "
              f"(gate + meas idle combined)")
        print(f"sum(marginal) = {sum(r[2] for r in rows):.3f}  "
              f"(>1 <=> shared mixed faults; Google renormalizes)")
        print(f"Willow-form sum: {sum(P_STAR / r[4] for r in rows if r[4]):.3f} = "
              + " + ".join(f"{P_STAR/r[4]:.3f} ({r[0].replace(' only', '')})" for r in rows if r[4])
              + ("   [all terms < 1: genuinely sub-threshold]"
                 if all(P_STAR / r[4] < 1 for r in rows if r[4])
                 else "   [WARNING: a term >= 1 — p* is not below every pseudo-threshold]"))

    def fig_budget(self):
        p_grid, P_STAR, rows = self.p_grid, self.P_STAR, self.rows6
        fig, (axL, axR) = plt.subplots(1, 2, figsize=(12, 4.5))
        # left: marginal budget fractions vs p — REWEIGHTED measured spectra (solid), the same
        # estimator as the table/bars at p*, so the panels agree. The f5-fit version is kept as
        # faint dashed lines (unclipped) to make the low-p extrapolation drift visible instead
        # of hiding it.
        Lf_rw = reweight_spectrum(self.tech1["full symmetric"]["spec"], p_grid).P_logical
        Lf_fit = self.tech1["full symmetric"]["LER"]
        for ch in self.CHANNELS:
            frac_rw = 1.0 - reweight_spectrum(self.tech1_abl[self.ABL_OF[ch]]["spec"],
                                              p_grid).P_logical / Lf_rw
            axL.plot(p_grid, frac_rw, "-", color=self.COLORS[ch], lw=2, label=ch)
            axL.plot(p_grid, 1.0 - self.tech1_abl[self.ABL_OF[ch]]["LER"] / Lf_fit,
                     "--", color=self.COLORS[ch], lw=1, alpha=0.4)
        axL.plot([], [], "--", color="gray", lw=1, alpha=0.6, label="f5-fit version (drifts at low p)")
        axL.axhline(0.0, color="gray", lw=0.8)
        axL.set_xscale("log"); axL.set_xlabel("physical error rate p")
        axL.set_ylabel("marginal fraction  1 − LER$_{no\\,i}$/LER$_{full}$")
        axL.axvline(P_STAR, color="gray", ls=":", lw=1); axL.legend(fontsize=8); axL.grid(alpha=0.3)
        # right: the budget bar chart at p*
        labels = [r[0] for r in rows] + ["mixing"]
        iso_v = [r[1] for r in rows] + [self.mixing]
        marg_v = [r[2] for r in rows] + [np.nan]
        x = np.arange(len(labels))
        axR.bar(x - 0.2, iso_v, 0.4, label="isolated (channel-only)")
        axR.bar(x + 0.2, marg_v, 0.4, yerr=[r[5] for r in rows] + [np.nan], capsize=3,
                label="marginal (leave-one-out)")
        axR.set_xticks(x, labels, rotation=20)
        axR.set_ylabel(f"fraction of LER_full at p*={P_STAR}")
        axR.legend(fontsize=8); axR.grid(alpha=0.3, axis="y")
        fig.suptitle("Kunlun [[18,4,4]] — Willow-style error budget")
        plt.tight_layout(); plt.show()

    # --- §7 the [[72,4,8]] sibling --------------------------------------------------------

    def tech2_72_table(self):
        self.tech2_72 = {name: self.load(f"tech2_72__{slug(name)}")["D"] for name in self.MODELS}
        print(f"{'model':16s} {'D':>2}   (circuit fault distance, BP-OSD upper bound; "
              f"f0 unpinned at this size)")
        for name in self.MODELS:
            print(f"{name:16s} {self.tech2_72[name]:2d}")

    def load_spectra_72(self):
        self.tech1_72, self.mc72 = {}, {}
        for name in self.MODELS:
            r = self.load(f"tech1_72__{slug(name)}")
            self.tech1_72[name] = dict(spec=self.spectrum_of(r), LER=np.asarray(r["LER_fit"]),
                                       cost=r["fit"]["cost"])
            self.mc72[name] = {float(p): v
                               for p, v in self.load(f"mc72__{slug(name)}")["points"].items()}
            n_planned, n_sampled = len(r["W"]), len(r["spectrum"]["weights"])
            print(f"{name:16s}: weights 1..{r['W'][-1]} ({n_sampled}/{n_planned} sampled, "
                  f"{r['shots']} shots), f5 fit cost={r['fit']['cost']:.2f}, "
                  f"MC LER(0.008)={self.mc72[name][0.008][0]:.3e}")
        print()
        print(self.section_time("tech2_72", "tech1_72", "mc72"))

    # --- the spectrum grid ----------------------------------------------------------------

    def _tech2_name(self, name):
        """The tech2 task carrying this spectrum's D/w0/f0* (or f0_lower), or None.

        D, w0 and the failing SETS are ray-independent (support-level combinatorics), but the
        onset FRACTION is not: mechanisms enter the expanded-uniform measure with
        rate-proportional multiplicities, so the ×5 ray re-weights the same failing sets. The
        asym 18-code mixes therefore load tech2_asym__*_18 (compute_f0_asym_18.py — reuses the
        symmetric D+L(D), redoes only the fail-count weighting). The [[72,4,8]] f0 is unpinned
        (no exact L(D) at that size) — the isolated/full tech2_72 tasks carry a LOWER-BOUND
        f0_lower (compute_f0_lower_72.py) and the ×5 asym 72 mixes their own ray-weighted one
        (tech2_asym__*_72, compute_f0_lower_asym_72.py — for the ablated mixes even D is a
        BP-OSD bound computed there); ablated-72 tasks have none."""
        if name.startswith("tech1_72_abl__"):
            return None                            # no ablated 72-code distance/onset computed
        if name.startswith("tech1_72__"):
            return name.replace("tech1_72__", "tech2_72__", 1)  # exact f0 unpinned; f0_lower here
        if name.startswith("tech1_abl__"):
            return name.replace("tech1_abl__", "tech2_abl__", 1)
        if name.startswith("tech1__"):
            return name.replace("tech1__", "tech2__", 1)
        if name.startswith("asym__"):              # _18: exact ray-weighted f0*; _72: f0_lower bound
            return name.replace("asym__", "tech2_asym__", 1)
        return None

    def _plot_spec(self, ax, name, color, label):
        try:
            r = self.load(name)
        except FileNotFoundError:
            return label                           # not cached (e.g. stale-decoder quarantine)
        s = self.spectrum_of(r)
        w, f, t = (np.asarray(a) for a in (s.weights, s.failures, s.trials))
        hit = f > 0
        fr = (f / t)[hit]
        # 95% binomial CI; lower bars clipped above zero so log-scale rendering survives
        # single-failure bins (whose CI floor would otherwise cross the axis)
        se = 1.96 * np.sqrt(np.clip(fr * (1 - fr), 0, None) / t[hit])
        ax.errorbar(w[hit], fr, yerr=[np.minimum(se, fr * 0.999), se], fmt=".-",
                    ms=4, lw=0.8, elinewidth=0.7, capsize=1.5, color=color, label=label)
        z = f == 0
        if z.any():
            ax.plot(w[z], 0.5 / t[z], "x", color=color, alpha=0.4)
        # ★ = Technique II's EXACT perfect-decoder onset fraction f0* at w0 (Prop.1 even D /
        # App.A.6 odd D). The ×5 asym rows load their OWN ray-weighted f0* (tech2_asym__*_18):
        # the failing sets are ray-independent but the fraction re-weights with the
        # rate-proportional multiplicities. ▲ (open, "f0* >=") = the [[72,4,8]] LOWER BOUND
        # f0_lower from a partial L(D) (compute_f0_lower_72.py) — exact f0* is unpinned at that
        # size, so panels get the floor.
        t2 = self._tech2_name(name)
        if t2:
            try:
                tr = self.load(t2)
                w0, f0, f0lo = tr.get("w0"), tr.get("f0"), tr.get("f0_lower")
                if w0 not in (None, "") and f0 not in (None, ""):
                    ax.plot(w0, float(f0), "*", color=color, ms=12, mec="k", mew=0.5, zorder=6)
                elif w0 not in (None, "") and f0lo not in (None, ""):
                    ax.plot(w0, float(f0lo), "^", color=color, ms=8, mfc="none", mec=color,
                            mew=1.4, zorder=6)
            except FileNotFoundError:
                pass
        try:
            if "fit" in r:
                fw = lambda wg, r=r: failure_spectrum_ansatz(
                    wg, a=1.0 - 2.0 ** -r["K"], model=r["fit"]["model"], **r["fit"]["params"])
            else:
                fw = fit_failure_spectrum(s, K=r["K"], model="f5", w0=None, f0=None).f
            wg = np.geomspace(1.0, float(w.max()), 200)
            y = np.asarray(fw(wg))
            ax.plot(wg[y > 0], y[y > 0], "--", lw=1.0, alpha=0.55, color=color)
        except Exception:
            pass                                   # too-sparse spectrum, no converged fit — dots only
        return None

    def fig_spectrum_grid(self):
        """ALL measured spectra in the report — every number in §6–§8 reweights one of these.

        Panels: rows = isolated+full models / leave-one-out mixes / asymmetric ×5 mixes;
        cols = [[18,4,4]] / [[72,4,8]]. Loaded straight from the cache (independent of the
        per-section loaders; curves whose task is not cached yet are listed as missing instead
        of crashing the figure). Dots: f(w)/T(w) where failures were observed; × = sampled zero
        bins (at 1/(2T)); thin dashed curve = f5 ansatz (stored fit where the runner fitted
        one, else fitted here on the cached bins); dashed vertical = the full model's predicted
        onset w0 = ceil(D/2) (from tech2 D), the PERFECT-decoder onset — dots LEFT of it are
        sub-onset decoder artifacts; star = exact onset f0* at w0 (18-code + ×5 asym); open
        triangle = 72-code f0_lower lower bound. The ansatz is identically zero below its
        fitted w0 — a dot the dashed curve cannot reach is outside the ansatz family, the
        decoder-floor signature. Check that region whenever the decoder config or sampling
        budgets change.
        """
        ABL_COLOR = {abl: self.COLORS[ch] for ch, abl in self.ABL_OF.items()}
        FULLC = self.COLORS["full symmetric"]
        ROWS = [
            ("isolated + full models",
             [(f"tech1__{slug(m)}", self.COLORS[m], m) for m in self.MODELS],
             [(f"tech1_72__{slug(m)}", self.COLORS[m], m) for m in self.MODELS]),
            ("leave-one-out mixes",
             [(f"tech1_abl__{slug(a)}", ABL_COLOR[a], a) for a in self.ABLATED],
             [(f"tech1_72_abl__{slug(a)}", ABL_COLOR[a], a) for a in self.ABLATED]),
            ("asymmetric ×5 mixes (meas, meas-idle ×5)",
             [("asym__full_18", FULLC, "full ×5")]
             + [(f"asym__{slug(a)}_18", ABL_COLOR[a], a) for a in self.ABLATED],
             [("asym__full_72", FULLC, "full ×5")]
             + [(f"asym__{slug(a)}_72", ABL_COLOR[a], a) for a in self.ABLATED]),
        ]
        # predicted onset w0 = ceil(D/2): lowest weight even a perfect min-weight decoder can
        # be forced to misjudge
        ONSET_BY_COL = [(self.load("tech2__full_symmetric")["D"] + 1) // 2,
                        (self.load("tech2_72__full_symmetric")["D"] + 1) // 2]

        # sharey per ROW, not per column: the x5 asym rays live between ~1e-2 and 1, while
        # the symmetric rows reach 1e-7. Sharing a column made the asym panels a flat line
        # pinned to the top of a six-decade axis. Rows still share so the two codes stay
        # directly comparable, which is the comparison the figure exists to make.
        # Layout: 2 tall x 3 wide — ROW = code ([[18,4,4]] then [[72,4,8]]), COLUMN = model
        # family. Each row shares x (a code's weight window) and y (its dynamic range), so
        # the three families of one code are directly comparable and neither code's scale
        # is imposed on the other.
        fig, axes = plt.subplots(2, 3, figsize=(17, 8.5), sharex="row", sharey="row")
        for code_i in (0, 1):
            for fam_i, (fam_title, specs18, specs72) in enumerate(ROWS):
                ax = axes[code_i][fam_i]
                specs = (specs18, specs72)[code_i]
                missing = [m for name, col, lbl in specs
                           if (m := self._plot_spec(ax, name, col, lbl))]
                ax.axvline(ONSET_BY_COL[code_i], color="k", ls="--", lw=0.8)
                ax.set_xscale("log"); ax.set_yscale("log")
                ax.set_title(f"{['[[18,4,4]]', '[[72,4,8]]'][code_i]} — {fam_title}",
                             fontsize=10)
                ax.grid(alpha=0.3, which="both")
                ax.legend(fontsize=7)
                if missing:
                    ax.text(0.03, 0.03, "missing: " + ", ".join(missing), transform=ax.transAxes,
                            fontsize=7, color="firebrick", va="bottom")
                if code_i == 1:
                    ax.set_xlabel("fault weight w")
            axes[code_i][0].set_ylabel("per-bin failure fraction  f(w)/T(w)")
        # The [[72,4,8]] f0* lower bounds span many decades (they tighten only with more
        # enumerated logicals), so the loosest ones (e.g. CZ's single weight-10 logical) would
        # crush the data if left to set the scale. Floor the 72-code column and note any bound
        # that falls below the axis; sharey="col" already keeps the 18-code column on its own
        # tight scale.
        Y72_FLOOR = 1e-9
        # the 72-code row now shares one y-axis across its three families, so floor it once
        # from the deepest point any of them actually reaches
        lo72 = min((v for ax in axes[1] for ln in ax.get_lines()
                    for v in ln.get_ydata() if v and v > 0), default=Y72_FLOOR)
        axes[1][0].set_ylim(bottom=max(Y72_FLOOR, lo72 / 5))

        def _note_clipped(ax, tasks):              # bounds under the floor -> a text note
            clipped = []
            for lbl, task in tasks:
                try:
                    fl = self.load(task).get("f0_lower")
                except FileNotFoundError:
                    continue
                if fl not in (None, "") and float(fl) < Y72_FLOOR:
                    clipped.append(f"{lbl} ≥ {float(fl):.0e}")
            if clipped:
                ax.text(0.03, 0.03, "f₀* lower bounds below axis: " + "; ".join(clipped),
                        transform=ax.transAxes, fontsize=6.5, va="bottom", color="dimgray")

        _note_clipped(axes[1][0], [(m, f"tech2_72__{slug(m)}") for m in self.MODELS])
        _note_clipped(axes[1][2], [("full ×5", "tech2_asym__full_72")]
                                  + [(a, f"tech2_asym__{slug(a)}_72") for a in self.ABLATED])
        # Full legend of every glyph, gathered on the two top panels (all glyphs recur in
        # every row).
        axes[0][0].plot([], [], "--", color="gray", lw=1, alpha=0.7, label="f5 ansatz")
        axes[0][0].plot([], [], "x", color="gray", ls="none",
                        label="sampled zero-failure bin (drawn at 1/2T)")
        axes[0][0].plot([], [], "--", color="k", lw=0.8,
                        label=r"predicted onset $w_0=\lceil D/2\rceil$")
        axes[0][0].plot([], [], "*", color="gray", mec="k", mew=0.5, ms=12, ls="none",
                        label="perfect-decoder onset f₀* (exact; 18-code)")
        axes[0][0].legend(fontsize=7)
        # the 72-code-only glyph belongs on the 72 row, which is now row 1
        axes[1][0].plot([], [], "^", color="gray", mfc="none", mec="gray", mew=1.4, ms=8,
                        ls="none",
                        label="perfect-decoder onset f₀* ≥ (lower bound; 72-code)")
        axes[1][0].legend(fontsize=7)
        plt.tight_layout(); plt.show()

    # --- §7.3 the Λ table -----------------------------------------------------------------

    def lambda_table(self):
        """Point-Λ per channel at p* + true-threshold crossings from the f5-fit curves.

        Λ evaluation point matches the §6 budget's p*, deep in the suppression regime. Point-Λ
        uses the REWEIGHTED measured spectra (both codes sampled from w=1 through their
        onsets), avoiding cross-fit extrapolation drift; the f5-based value is printed as a
        cross-check. The ±σ column propagates the binomial errors of both spectra. Honesty
        note: zero-failure onset bins make the reweighted ε72 a lower bound → Λ an upper bound
        (a large reweighted-vs-fit gap flags this; the §7.5 box quantifies it per channel via
        the rule-of-three zero-bin headroom).
        """
        p_grid, P_LAM = self.p_grid, self.P_LAM
        self.eps18 = {m: per_round(self.tech1[m]["LER"], self.ROUNDS) for m in self.MODELS}
        self.eps72 = {m: per_round(self.tech1_72[m]["LER"], self.ROUNDS72) for m in self.MODELS}
        eps18, eps72 = self.eps18, self.eps72

        i_lam = int(np.argmin(np.abs(p_grid - P_LAM)))
        rows7, inv7 = [], {}
        print(f"{'channel':16s} {'p_th (ε18=ε72)':>15} {'Λ(p*)':>9} {'±σ':>8} {'Λ(fit)':>9} "
              f"{'p*/p_th':>9}     (p* = {P_LAM})")
        for m in self.MODELS:
            pth = crossing_p(p_grid, eps18[m], eps72[m])
            inv, inv_se, inv_lo, inv_hi = self.inv_lambda_stats(
                self.tech1[m]["spec"], self.tech1_72[m]["spec"], P_LAM)
            inv7[m] = (inv, inv_se, inv_lo, inv_hi)
            lam, lam_se = 1.0 / inv, inv_se / inv**2
            lam_fit = float(eps18[m][i_lam] / eps72[m][i_lam])
            rows7.append((m, pth, lam))
            pths = f"{pth:.4f}" if pth else f">{p_grid.max():.3g}"
            term = f"{P_LAM/pth:.3f}" if pth else f"<{P_LAM/p_grid.max():.3f}"
            print(f"{m:16s} {pths:>15} {lam:9.3g} {lam_se:8.2g} {lam_fit:9.3g} {term:>9}")
        self.rows7, self.inv7 = rows7, inv7

        self.lam_full = dict((m, l) for m, _, l in rows7)["full symmetric"]
        print(f"\nΛ_full(p*) = {self.lam_full:.3g}  →  per-(+2-distance)-step λ = √Λ = "
              f"{np.sqrt(self.lam_full):.3g}  (d: 4→8 is two steps)")
        inv_lam = 1.0 / self.lam_full
        terms = {m: P_LAM / pth for m, pth, _ in rows7 if pth is not None and m != "full symmetric"}
        spam_term = terms.get("meas only", 0) + terms.get("prep only", 0)
        print(f"Willow identity check at p*: 1/Λ_full = {inv_lam:.3f}  vs  Σᵢ p*/p_th,i = "
              f"{sum(terms.values()):.3f}"
              f"   (CZ {terms.get('CZ only', float('nan')):.3f}, SPAM {spam_term:.3f})")
        print("residual = mixed-channel faults (isolated channels cannot see them — see §1/§5); "
              "Σ < 1/Λ_full means the additive budget under-covers by that share.")

    # --- §7.4 the ε/λ panels --------------------------------------------------------------

    def fig_74(self):
        """ε pairs + per-step 1/λ on the symmetric ray, bold reweighted + faint f5 fit.

        BOLD = reweighted MEASURED spectra — the same estimator as every §6–§8 table, no
        extrapolation. FAINT = the independently-fitted f5 curves: below p ≈ 5e-4 they drift
        apart (the full 72-code fit cannot represent the w=3 decoder floor — fit cost 76 — so
        its extrapolation dives and even crosses the isolated channels' fits, a spurious
        inversion this panel used to present as physics; the measured spectra show
        full ≥ every isolated channel across the whole grid). Codes keep their linestyle:
        [[18,4,4]] solid, [[72,4,8]] dashed; estimator is encoded by line weight. Low-p
        caveat: zero-failure onset bins make reweighted ε72 a LOWER bound down there (so 1/λ
        on the right is a lower bound too — §7.5's truncation interval prices exactly this).
        """
        p_grid, P_LAM = self.p_grid, self.P_LAM
        self.eps18_rw = {m: per_round(reweight_spectrum(self.tech1[m]["spec"], p_grid).P_logical,
                                      self.ROUNDS) for m in self.MODELS}
        self.eps72_rw = {m: per_round(
            reweight_spectrum(fill_spectrum(self.tech1_72[m]["spec"]), p_grid).P_logical,
            self.ROUNDS72) for m in self.MODELS}

        fig, (axL, axR) = plt.subplots(1, 2, figsize=(13, 5))
        for m in self.MODELS:
            col = self.COLORS[m]
            axL.plot(p_grid, self.eps18_rw[m], "-", color=col, lw=2, label=m)
            axL.plot(p_grid, self.eps72_rw[m], "--", color=col, lw=1.8)
            axL.plot(p_grid, self.eps18[m], "-", color=col, lw=0.8, alpha=0.3)
            axL.plot(p_grid, self.eps72[m], "--", color=col, lw=0.8, alpha=0.3)
            mp = sorted(self.mc72[m])
            axL.plot(mp, [per_round(np.asarray([self.mc72[m][p][0]]), self.ROUNDS72)[0]
                          for p in mp], "^", color=col, ms=6)
            ok = self.eps72_rw[m] > 0
            axR.plot(p_grid[ok], np.sqrt(self.eps72_rw[m][ok] / self.eps18_rw[m][ok]),
                     "-", color=col, lw=2, label=m)
            axR.plot(p_grid, np.sqrt(self.eps72[m] / self.eps18[m]), "-", color=col,
                     lw=0.8, alpha=0.3)
        axL.plot([], [], "-", color="gray", lw=2, label="reweighted measured (bold)")
        axL.plot([], [], "-", color="gray", lw=0.8, alpha=0.4, label="f5 fit (faint; drifts at low p)")
        axL.set_xscale("log"); axL.set_yscale("log")
        axL.set_xlabel("physical error rate p"); axL.set_ylabel("per-round logical error rate ε")
        axL.set_title("[[18,4,4]] (solid, 2 rounds) vs [[72,4,8]] (dashed, 4 rounds; ▲=MC)")
        axL.legend(fontsize=8); axL.grid(alpha=0.3, which="both")
        axR.set_xscale("log"); axR.set_yscale("log")
        axR.axhline(1.0, color="gray", lw=1); axR.axvline(P_LAM, color="gray", ls=":", lw=1)
        # 1/√Λ = per-(+2-distance)-step suppression DEFICIT (d: 4→8 is two steps) — the inverse
        # of the per-step λ Google quotes for the surface-code ladder (Willow: λ ≈ 2.14 →
        # 1/λ ≈ 0.47). 1/λ=1 crossings = p_th; below 1 = suppressing, and the low-p slope
        # reads as the order.
        axR.set_xlabel("physical error rate p")
        axR.set_ylabel(r"$1/\lambda(p) = \sqrt{\varepsilon_{72}/\varepsilon_{18}}$"
                       r"  (per +2-distance step)")
        axR.set_title("per-step suppression deficit (crossings at $1/\\lambda=1$ = true $p_{th,i}$)")
        axR.legend(fontsize=8); axR.grid(alpha=0.3, which="both")
        plt.tight_layout(); plt.show()

    # --- §7.5 marginal Λ ------------------------------------------------------------------

    def load_ablations_72(self):
        self.tech1_72_abl = {name: dict(spec=self.spectrum_of(self.load(f"tech1_72_abl__{slug(name)}")))
                             for name in self.ABLATED}
        print(self.section_time("tech1_72_abl"))

    def _lambda_decomposition(self, spec18_full, spec72_full, spec18_of, spec72_of, p):
        """The marginal-Λ box: contribution_i = 1/Λ_full − 1/Λ_no-i with ±σ and zero-bin interval."""
        inv_f, se_f, lo_f, hi_f = self.inv_lambda_stats(spec18_full, spec72_full, p)
        print(f"{'channel':12s} {'Λ_no-i(p*)':>11} {'1/Λ_no-i':>10} {'contribution':>13} {'±σ':>9} "
              f"{'share':>7}   verdict")
        tot = 0.0
        for ch in self.CHANNELS:
            inv_a, se_a, lo_a, hi_a = self.inv_lambda_stats(spec18_of(ch), spec72_of(ch), p)
            c = inv_f - inv_a
            sc = float(np.hypot(se_f, se_a))
            c_lo, c_hi = lo_f - hi_a, hi_f - lo_a  # zero-bin truncation interval around c
            tot += c
            if abs(c) < 2 * sc:
                verdict = "~0 within 2σ (noise)"
            elif c_lo < 0.0 < c_hi:
                verdict = "sign not robust to zero-bin truncation"
            else:
                verdict = "solid"
            print(f"{ch:12s} {1.0/inv_a:11.3g} {inv_a:10.3e} {c:13.3e} {sc:9.2e} "
                  f"{c/inv_f:7.2f}   {verdict}")
        print(f"\nsum of marginal contributions = {tot:.3e}  vs  1/Λ_full = {inv_f:.3e}"
              f"   (ratio {tot/inv_f:.2f})")
        print("ratio > 1: shared mixed faults counted once per participant (as in §6's "
              "Σ marginal > 1).")
        print("A NEGATIVE contribution is physical only when 'solid': removing that channel genuinely")
        print("HURT the suppression ratio (the big code handles its faults better than the small one).")
        print("'~0' / 'not robust' rows are sampling artifacts — tighten with run_error_model_comparison")
        print("--boost72 (2× failures, 5× shots on every 72-code spectrum feeding this box).")
        return inv_f

    def lambda_box_sym(self):
        print(f"marginal Λ decomposition at p* = {self.P_LAM}   (Λ_full = {self.lam_full:.3g}, "
              f"1/Λ_full = {1/self.lam_full:.3e})")
        self._lambda_decomposition(self.tech1["full symmetric"]["spec"],
                                   self.tech1_72["full symmetric"]["spec"],
                                   lambda ch: self.tech1_abl[self.ABL_OF[ch]]["spec"],
                                   lambda ch: self.tech1_72_abl[self.ABL_OF[ch]]["spec"], self.P_LAM)

    # --- §8 the asymmetric operating point ------------------------------------------------

    def load_asym(self):
        self.asym = {}
        for label in ("18", "72"):
            self.asym[("full", label)] = self.spectrum_of(self.load(f"asym__full_{label}"))
            for abl_name in self.ABLATED:
                self.asym[(abl_name, label)] = self.spectrum_of(
                    self.load(f"asym__{slug(abl_name)}_{label}"))
        print(self.section_time("asym"))

    def budget_box_asym(self):
        """The budget at the asymmetric point.

        Isolated fractions reuse the §2 spectra, reweighted at each channel's OWN rate
        (r_i * p*); marginals come from the new asymmetric ablated mixes.
        """
        P_STAR = self.P_STAR
        L_asym, L_asym_se, _ = self.rw_stats(self.asym[("full", "18")], P_STAR)
        rows8 = []
        for ch in self.CHANNELS:
            iso = float(reweight_spectrum(self.tech1[ch]["spec"],
                                          [self.R_OF[ch] * P_STAR]).P_logical[0]) / L_asym
            La, La_se, _ = self.rw_stats(self.asym[(self.ABL_OF[ch], "18")], P_STAR)
            marg = 1.0 - La / L_asym
            marg_se = (La / L_asym) * float(np.hypot(La_se / La, L_asym_se / L_asym))
            rows8.append((ch, iso, marg, marg_se))
        mix8 = 1.0 - sum(r[1] for r in rows8)
        sym = {r[0]: (r[1], r[2]) for r in self.rows6}   # §6's symmetric-point rows for comparison
        print(f"budget at the ASYMMETRIC point (meas, meas_idle ×5), p* = {P_STAR}:")
        print(f"LER_full = {L_asym:.3e}  (symmetric point: {self.L_full:.3e} — the ×5 mix costs "
              f"{L_asym/self.L_full:.1f}× in error rate)")
        print(f"{'channel':12s} {'isolated':>9} {'marginal':>9} {'±σ':>6}   vs symmetric "
              f"{'iso':>6} {'marg':>6}")
        for ch, iso, marg, mse in rows8:
            print(f"{ch:12s} {iso:9.3f} {marg:9.3f} {mse:6.3f}                "
                  f"{sym[ch][0]:6.3f} {sym[ch][1]:6.3f}")
        print(f"{'mixing':12s} {mix8:9.3f}                               {self.mixing:6.3f}")
        print(f"sum(marginal) = {sum(r[2] for r in rows8):.3f}   "
              f"(symmetric: {sum(r[2] for r in self.rows6):.3f})")

    def lambda_box_asym(self):
        """Λ at the asymmetric point + its marginal decomposition (both codes' asym ablations),
        with the same ±σ and zero-bin verdicts as §7.5 — read the two boxes together to see how
        the gradient of 1/Λ rotates when the noise mix moves from the symmetric ray to the
        device-like ray."""
        P_LAM = self.P_LAM
        inv8, inv8_se, _, _ = self.inv_lambda_stats(self.asym[("full", "18")],
                                                    self.asym[("full", "72")], P_LAM)
        lam8 = 1.0 / inv8
        print(f"Λ_full(p*={P_LAM}) at the ×5 point: {lam8:.3g} ± {inv8_se/inv8**2:.2g}   "
              f"(symmetric: {self.lam_full:.3g})"
              f"   per-step λ = {np.sqrt(lam8):.3g} (symmetric: {np.sqrt(self.lam_full):.3g})")
        self._lambda_decomposition(self.asym[("full", "18")], self.asym[("full", "72")],
                                   lambda ch: self.asym[(self.ABL_OF[ch], "18")],
                                   lambda ch: self.asym[(self.ABL_OF[ch], "72")], P_LAM)

    # --- §8.4 the ×5-ray panels -----------------------------------------------------------

    def fig_84(self):
        """The §7.4 panels on the ×5 ray, dual-estimator style (bold reweighted + faint fit).

        ε-curve pairs on the ×5 ray. Isolated channels: reweight at r_i·p (no new data).
        Mixes: reweight the asymmetric spectra along the ray. Mask boosted channels where
        r_i·p exceeds the sampled window coverage. FAINT curves — the f5-fit estimator on the
        ray: isolated channels shift their stored fit curves to r_i·p (log-log interpolation
        of the §7 fit curves — identical fits, scaled abscissa; exact on the geometric grid),
        while the full ×5 mix has no stored fit (runner with_fit=False) so it is fitted here
        on the cached asym bins — same call as the spectrum grid — and pushed through the
        ansatz reweighting.
        """
        p_grid, P_LAM = self.p_grid, self.P_LAM
        X5 = "full ×5 mix"
        R_OF_ALL = dict(self.R_OF, **{X5: 1.0})
        eps18_x5 = {X5: per_round(
            reweight_spectrum(fill_spectrum(self.asym[("full", "18")]), p_grid).P_logical,
            self.ROUNDS)}
        eps72_x5 = {X5: per_round(
            reweight_spectrum(fill_spectrum(self.asym[("full", "72")]), p_grid).P_logical,
            self.ROUNDS72)}
        for ch in self.CHANNELS:
            eps18_x5[ch] = per_round(
                reweight_spectrum(self.tech1[ch]["spec"], self.R_OF[ch] * p_grid).P_logical,
                self.ROUNDS)
            eps72_x5[ch] = per_round(
                reweight_spectrum(fill_spectrum(self.tech1_72[ch]["spec"]),
                                  self.R_OF[ch] * p_grid).P_logical, self.ROUNDS72)
        VALID = {m: R_OF_ALL[m] * p_grid <= p_grid.max() * (1 + 1e-9) for m in eps18_x5}

        def _fit_on_ray(eps_fit, r):
            return np.exp(np.interp(np.log(r * p_grid), np.log(p_grid),
                                    np.log(np.maximum(eps_fit, TINY))))
        eps18_fit_x5 = {ch: _fit_on_ray(self.eps18[ch], self.R_OF[ch]) for ch in self.CHANNELS}
        eps72_fit_x5 = {ch: _fit_on_ray(self.eps72[ch], self.R_OF[ch]) for ch in self.CHANNELS}
        for lbl, rounds_, out in (("18", self.ROUNDS, eps18_fit_x5),
                                  ("72", self.ROUNDS72, eps72_fit_x5)):
            try:
                r = self.load(f"asym__full_{lbl}")
                fit = fit_failure_spectrum(self.spectrum_of(r), K=r["K"], model="f5",
                                           w0=None, f0=None)
                out[X5] = per_round(logical_error_rate_from_ansatz(fit, p_grid), rounds_)
            except Exception as e:                 # too-sparse spectrum / no converged fit
                print(f"full ×5 mix ({lbl}-code): f5 fit skipped ({e}) — faint curve omitted")

        print(f"true per-channel thresholds on the ×5 ray (base-p convention) vs the symmetric ray")
        print(f"{'channel':14s} {'p_th ×5':>10} {'p_th sym (rw)':>14}   note")
        for m in [X5] + self.CHANNELS:
            v = VALID[m]
            pth = crossing_p(p_grid[v], np.maximum(eps18_x5[m][v], TINY),
                             np.maximum(eps72_x5[m][v], TINY))
            sym_m = "full symmetric" if m == X5 else m
            pth_s = crossing_p(p_grid, np.maximum(self.eps18_rw[sym_m], TINY),
                               np.maximum(self.eps72_rw[sym_m], TINY))
            top = p_grid[v].max()
            pths = f"{pth:.4f}" if pth else f">{top:.3g}"
            pss = f"{pth_s:.4f}" if pth_s else f">{p_grid.max():.3g}"
            note = ("×5 channel: threshold in its OWN rate = 5×p_th" if R_OF_ALL[m] > 1 else "")
            print(f"{m:14s} {pths:>10} {pss:>14}   {note}")
        print("NB: these crossings sit near the K=4 saturation pinch (ε72 caps at 1−(2^-K)^{1/4}), so they")
        print("are estimator-sensitive — §7's f5-fit versions (full 0.0227, CZ 0.0379) may differ; treat")
        print("either as indicative. 1/λ at very low p is a LOWER bound (zero-bin truncation of ε72).")

        fig, (axL, axR) = plt.subplots(1, 2, figsize=(13, 5))
        CLR = dict(self.COLORS, **{X5: "crimson"})
        for m in [X5] + self.CHANNELS:
            col, v = CLR[m], VALID[m]
            lw = 2.5 if m == X5 else 2
            axL.plot(p_grid[v], eps18_x5[m][v], "-", color=col, lw=lw, label=m)
            axL.plot(p_grid[v], eps72_x5[m][v], "--", color=col, lw=lw * 0.7)
            inv_lam = np.sqrt(np.maximum(eps72_x5[m][v], TINY) / np.maximum(eps18_x5[m][v], TINY))
            axR.plot(p_grid[v], inv_lam, "-", color=col, lw=lw, label=m)
            if m in eps18_fit_x5 and m in eps72_fit_x5:    # faint f5-fit twins, §7.4 style
                axL.plot(p_grid[v], eps18_fit_x5[m][v], "-", color=col, lw=0.8, alpha=0.3)
                axL.plot(p_grid[v], eps72_fit_x5[m][v], "--", color=col, lw=0.8, alpha=0.3)
                axR.plot(p_grid[v], np.sqrt(np.maximum(eps72_fit_x5[m][v], TINY)
                                            / np.maximum(eps18_fit_x5[m][v], TINY)),
                         "-", color=col, lw=0.8, alpha=0.3)
        axL.plot([], [], "-", color="gray", lw=2, label="reweighted measured (bold)")
        axL.plot([], [], "-", color="gray", lw=0.8, alpha=0.4, label="f5 fit (faint; drifts at low p)")
        axL.set_xscale("log"); axL.set_yscale("log")
        axL.set_xlabel("base physical error rate p (boosted channels at 5p)")
        axL.set_ylabel("per-round logical error rate ε")
        axL.set_title("×5 ray: [[18,4,4]] (solid) vs [[72,4,8]] (dashed) — reweighted spectra")
        axL.legend(fontsize=8); axL.grid(alpha=0.3, which="both")
        axR.set_xscale("log"); axR.set_yscale("log")
        axR.axhline(1.0, color="gray", lw=1); axR.axvline(P_LAM, color="gray", ls=":", lw=1)
        axR.set_xlabel("base physical error rate p")
        axR.set_ylabel(r"$1/\lambda(p) = \sqrt{\varepsilon_{72}/\varepsilon_{18}}$"
                       r"  (per +2-distance step)")
        axR.set_title("per-step suppression DEFICIT on the ×5 ray "
                      "($1/\\lambda=1$ crossings = $p_{th,i}$)")
        axR.legend(fontsize=8); axR.grid(alpha=0.3, which="both")
        plt.tight_layout(); plt.show()

    # --- §8.5 the marginal curves ---------------------------------------------------------

    def fig_85(self):
        """Marginal (leave-one-out) curves along BOTH rays from the cached ablation spectra.

        LER fractions per code + 1/Λ deficit shares, with ±1σ bands — binomial errors
        propagated exactly as in the §7.5/§8 boxes (hypot of the two relative errors; the
        full-mix/ablation correlation is neglected, same convention). Bands are STATISTICAL
        only: the zero-bin truncation exposure is not drawn — the boxes' [lo, hi] verdicts
        carry it. y-range clamped; a band swallowing its curve = noise-dominated region
        (prep, and everything at low p).
        """
        p_grid, P_LAM = self.p_grid, self.P_LAM

        def _eps(L, se, rounds):
            Lc = np.clip(L, 0.0, 1.0 - 1e-12)
            g = (1.0 - Lc) ** (1.0 / rounds - 1.0) / rounds
            return 1.0 - (1.0 - Lc) ** (1.0 / rounds), g * se

        # spectrum lookup per ray: (mix, code) -> FailureSpectrum, mix in {"full"} ∪ ABLATED
        def _spec_sym(m, c):
            if m == "full":
                return (self.tech1 if c == "18" else self.tech1_72)["full symmetric"]["spec"]
            return (self.tech1_abl if c == "18" else self.tech1_72_abl)[m]["spec"]

        MIX = ["full"] + list(self.ABLATED)
        for ray, spec_of in [("symmetric ray", _spec_sym),
                             ("×5 ray", lambda m, c: self.asym[(m, c)])]:
            def _rw(m, code):
                v = reweight_spectrum(fill_spectrum(spec_of(m, code)), p_grid)
                return np.asarray(v.P_logical), np.asarray(v.P_logical_se)
            L18 = {m: _rw(m, "18") for m in MIX}
            L72 = {m: _rw(m, "72") for m in MIX}
            E18 = {m: _eps(*L18[m], self.ROUNDS) for m in MIX}
            E72 = {m: _eps(*L72[m], self.ROUNDS72) for m in MIX}
            INV = {}
            for m in MIX:
                (e1, s1), (e2, s2) = E18[m], E72[m]
                iv = np.maximum(e2, TINY) / np.maximum(e1, TINY)
                INV[m] = (iv, iv * np.hypot(s1 / np.maximum(e1, TINY), s2 / np.maximum(e2, TINY)))

            fig, (axL, axR) = plt.subplots(1, 2, figsize=(13, 5))
            for ch in self.CHANNELS:
                # legend: plain channel names — every curve here is the LEAVE-ONE-OUT (no-i)
                # marginal for that channel, not the isolated "<ch> only" model the §7.4/§8.4
                # panels plot.
                a, col, lbl = self.ABL_OF[ch], self.COLORS[ch], ch.replace(" only", "")
                for (Lf, sLf), (La, sLa), ls, lw, lab in [
                    (L18["full"], L18[a], "-", 2.0, lbl),
                    (L72["full"], L72[a], "--", 1.2, None),
                ]:
                    frac = 1.0 - La / Lf
                    sfrac = (La / Lf) * np.hypot(sLa / np.maximum(La, TINY),
                                                 sLf / np.maximum(Lf, TINY))
                    axL.plot(p_grid, frac, ls, color=col, lw=lw, label=lab)
                    axL.fill_between(p_grid, frac - sfrac, frac + sfrac, color=col, alpha=0.12, lw=0)
                (ivf, sivf), (iva, siva) = INV["full"], INV[a]
                share = (ivf - iva) / ivf
                sshare = np.hypot(sivf, siva) / ivf
                axR.plot(p_grid, share, "-", color=col, lw=2, label=lbl)
                axR.fill_between(p_grid, share - sshare, share + sshare, color=col, alpha=0.12, lw=0)
            axL.plot([], [], "-", color="gray", label="[[18,4,4]]")
            axL.plot([], [], "--", color="gray", label="[[72,4,8]]")
            for ax, ylab, title in [
                (axL, "marginal LER fraction  $1 - \\mathrm{LER}_{no\\,i}/\\mathrm{LER}_{full}$",
                 f"{ray}: what limits each code's error rate"),
                (axR, "share of deficit  $(1/\\Lambda_{full} - 1/\\Lambda_{no\\,i})\\,/\\,"
                      "(1/\\Lambda_{full})$",
                 f"{ray}: what limits the suppression"),
            ]:
                ax.set_xscale("log"); ax.axhline(0.0, color="gray", lw=0.8)
                ax.axvline(P_LAM, color="gray", ls=":", lw=1)
                ax.set_xlabel("base physical error rate p"); ax.set_ylabel(ylab); ax.set_title(title)
                ax.set_ylim(-1.2, 1.8); ax.legend(fontsize=8); ax.grid(alpha=0.3)
            plt.tight_layout(); plt.show()


# ---------------------------------------------------------------------------
# Decoder A/B: two Report generations side by side (used by emc_decoder_ab.ipynb)
# ---------------------------------------------------------------------------

def _ab_specs(R, family):
    """(label, spec) list for one 72-code family of a Report (loaders must have run)."""
    if family == "models":
        return [(m, R.tech1_72[m]["spec"]) for m in R.MODELS]
    if family == "ablated":
        return [(a, R.tech1_72_abl[a]["spec"]) for a in R.ABLATED]
    if family == "asym":
        return [("full ×5", R.asym[("full", "72")])] + \
               [(a, R.asym[(a, "72")]) for a in R.ABLATED]
    raise ValueError(family)


def _ab_panel(ax, spec_b, spec_s, title):
    """One A/B panel: baseline decoder (gray, open) vs new decoder (crimson, filled).

    Dots = measured f(w) with binomial errors; × = sampled zero-failure bins drawn at
    1/(2T) — BOUNDS, not measurements, and the two generations' budgets differ (the
    baseline bins carry boost72 + 3e6-shot topups; the sys generation ran 1x adaptive),
    so a baseline dot with no partner dot usually means the new run's budget could not
    resolve that bin, not that the new decoder is clean there.
    """
    for spec, col, lbl, mk, mfc in ((spec_b, "0.45", "baseline decoder", "o", "none"),
                                    (spec_s, "crimson", "ghw decoder", "D", "crimson")):
        w = np.asarray(spec.weights, float)
        F = np.asarray(spec.failures, float)
        T = np.asarray(spec.trials, float)
        f = F / np.maximum(T, 1)
        hit, zero = F > 0, F == 0
        ax.errorbar(w[hit], f[hit], yerr=np.sqrt(np.clip(f[hit] * (1 - f[hit]), 0, None) / T[hit]),
                    fmt=mk, ms=3.2, lw=0.8, color=col, mfc=mfc, mew=0.9, label=lbl)
        if zero.any():
            ax.plot(w[zero], 0.5 / T[zero], "x", ms=3, color=col, alpha=0.45)
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_title(title, fontsize=9)
    ax.grid(alpha=0.25, which="both")


def fig_ab_72(R_base, R_new, family="models"):
    """Grid of 72-code failure-spectrum A/B panels for one family.

    families: "models" (6 isolated+full), "ablated" (5 leave-one-out),
    "asym" (full ×5 + 5 ablated ×5 mixes). The 18-code side is deliberately absent:
    both generations share the baseline decoder there and the spectra are
    bit-identical — nothing to compare.
    """
    sb = dict(_ab_specs(R_base, family))
    ss = dict(_ab_specs(R_new, family))
    names = [n for n in sb if n in ss]
    ncol = 3
    nrow = -(-len(names) // ncol)
    fig, axes = plt.subplots(nrow, ncol, figsize=(13, 3.6 * nrow), sharex=True, sharey=True)
    axes = np.atleast_2d(axes)
    for i, n in enumerate(names):
        _ab_panel(axes[i // ncol][i % ncol], sb[n], ss[n], n)
    for j in range(len(names), nrow * ncol):
        axes[j // ncol][j % ncol].axis("off")
    axes[0][0].legend(fontsize=7)
    for r in range(nrow):
        axes[r][0].set_ylabel("f(w)")
    for c in range(ncol):
        axes[-1][c].set_xlabel("fault weight w")
    fig.suptitle(f"[[72,4,8]] {family}: baseline vs ghw decoder "
                 "(× = zero-failure bins at 1/2T — bounds, budgets differ between generations)",
                 fontsize=10)
    plt.tight_layout(); plt.show()


def fig_split_crosscheck(R_base, R_new):
    """Technique-III (Metropolis splitting) LER cross-check, both codes.

    Left: [[18,4,4]] — the campaign's cached tech3 ladders (baseline decoder; identical
    in both generations) over the reweighted-measured LER curves. Right: [[72,4,8]]
    full symmetric — the ghw splitting ladder (runs/splitting_crosscheck/72_full_ghw.json)
    over the sys generation's reweighted curve, with the baseline generation's curve for
    reference. Splitting is decoder-in-the-loop and weight-agnostic: agreement validates
    the IS curves inside their windows; a low-p splitting EXCESS over the reweighted
    curve is the signature of failure mass the IS window missed (e.g. a sub-onset
    decoder floor). Ladder points beyond each run's honesty gate (swap-accept /
    mean-weight monotonicity) are drawn hollow — read those as unconverged, not data.
    """
    import pathlib
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(13, 5))
    pg = R_base.p_grid

    # left: 18-code, all models — tech3 ladders vs reweighted curves
    for m in R_base.MODELS:
        col = R_base.COLORS[m]
        rw = reweight_spectrum(R_base.tech1[m]["spec"], pg).P_logical
        axL.plot(pg, rw, "-", lw=1.1, color=col, alpha=.65, label=m)
        t3 = R_base.tech3[m]
        axL.errorbar(t3["sp"], t3["sP"], yerr=None, fmt="s", ms=3.5, mfc="none",
                     color=col, lw=0, elinewidth=.8)
    axL.plot([], [], "s", mfc="none", color="gray", label="splitting (Tech III)")
    axL.plot([], [], "-", color="gray", lw=1.1, label="reweighted IS")
    axL.set(xscale="log", yscale="log", xlabel="physical error rate p",
            ylabel="LER", title="[[18,4,4]] — splitting vs reweighted IS (baseline decoder)")
    axL.legend(fontsize=6.5, loc="upper left"); axL.grid(alpha=.25, which="both")

    # right: 72-code full symmetric — ghw splitting vs both generations' curves
    sb = R_base.tech1_72["full symmetric"]["spec"]
    ss = R_new.tech1_72["full symmetric"]["spec"]
    axR.plot(pg, reweight_spectrum(fill_spectrum(sb), pg).P_logical, "-", lw=1.1,
             color="0.45", label="baseline gen (reweighted, deep bins)")
    axR.plot(pg, reweight_spectrum(fill_spectrum(ss), pg).P_logical, "-", lw=1.4,
             color="crimson", label="ghw gen (reweighted; low bins pending top-up)")
    sc = pathlib.Path(run_dir("splitting_crosscheck"))
    f = sc / "72_full_ghw.json"
    if f.exists():
        j = json.loads(f.read_text(encoding="utf-8"))
        sp = np.asarray(j["sp"]); sP = np.asarray(j["sP"]); se = np.asarray(j["sP_se"])
        n = len(sp)
        gate_rung = j["gate_rung"]                  # rung index in DESCENDING ladder
        ok = np.arange(n) >= (n - 1 - gate_rung)    # ascending sp: quotable = top slice
        axR.errorbar(sp[ok], sP[ok], yerr=se[ok], fmt="D", ms=5, color="darkgreen",
                     lw=0, elinewidth=1.0, capsize=2.5,
                     label=f"ghw splitting (quotable to p={j['p_quotable_min']:.1e})")
        if (~ok).any():
            axR.errorbar(sp[~ok], sP[~ok], yerr=se[~ok], fmt="D", ms=5, mfc="none",
                         color="darkgreen", lw=0, elinewidth=.8, alpha=.6,
                         label="splitting beyond gate (unconverged)")
        axR.text(.03, .03, f"swap {min(j['swap_accept']):.2f}..{max(j['swap_accept']):.2f}   "
                           f"gate: {j['gate_reason']}", transform=axR.transAxes, fontsize=6.5)
    else:
        axR.text(.05, .5, "runs/splitting_crosscheck/72_full_ghw.json not present yet",
                 transform=axR.transAxes, fontsize=9)
    axR.set(xscale="log", yscale="log", xlabel="physical error rate p",
            ylabel="LER", title="[[72,4,8]] full symmetric — ghw splitting vs IS generations")
    axR.legend(fontsize=6.5, loc="upper left"); axR.grid(alpha=.25, which="both")
    plt.tight_layout(); plt.show()


def ab_ratio_table(R_base, R_new, family="models"):
    """Measured-bin ratio table: f_new/f_base where BOTH generations saw failures.

    Only both-measured bins are compared (ratios of bounds are meaningless); the
    'first measured w' columns show how much deeper the baseline generation's budgets
    reach — the sub-onset region is bound-limited in the new generation until its
    top-up runs.
    """
    sb = dict(_ab_specs(R_base, family))
    ss = dict(_ab_specs(R_new, family))
    print(f"{'model':16s} {'w':>5} {'f_base':>12} {'f_ghw':>12} {'ratio':>7} {'±':>6}")
    for n in sb:
        if n not in ss:
            continue
        db = {w: (f, t) for w, f, t in zip(sb[n].weights, sb[n].failures, sb[n].trials)}
        ds = {w: (f, t) for w, f, t in zip(ss[n].weights, ss[n].failures, ss[n].trials)}
        both = [w for w in sorted(set(db) & set(ds)) if db[w][0] > 0 and ds[w][0] > 0]
        first_b = min((w for w, (f, t) in sorted(db.items()) if f > 0), default=None)
        first_s = min((w for w, (f, t) in sorted(ds.items()) if f > 0), default=None)
        shown = 0
        for w in both:
            fb, tb = db[w]; fs, ts = ds[w]
            rb, rs = fb / tb, fs / ts
            ratio = rs / rb
            se = ratio * float(np.hypot(1 / np.sqrt(fb), 1 / np.sqrt(fs)))
            print(f"{n if shown == 0 else '':16s} {w:>5} {fb:>6}/{tb:<6} {fs:>6}/{ts:<6}"
                  f" {ratio:>7.2f} {se:>6.2f}")
            shown += 1
            if shown >= 4:
                break
        if shown == 0:
            print(f"{n:16s}   no both-measured bins")
        print(f"{'':16s}   first measured w: base {first_b}, ghw {first_s}")


# ---------------------------------------------------------------------------
# Device-calibration transition (EMC_CALIB=device, 2026-07-31)
# ---------------------------------------------------------------------------
DEV_CHANNELS72 = ["CZ only", "meas only", "prep only", "gate idle", "meas idle"]


class DevTransition:
    """Priors-vs-structure decomposition: the same five [[72,4,8]] sub-models decoded
    by their retired per-model specialist decoders vs the ONE device decoder (full-
    symmetric priors at DECODER_P). Same circuits, same sampling seeds — every
    difference is the decoder's priors. Full-symmetric anchors are convention-
    invariant and load from the sys/baseline caches."""

    def __init__(self,
                 dev="error_model_comparison_18_4_4_device_baseline18_ghw72",
                 retired=("_retired_permodel_calib/"
                          "error_model_comparison_18_4_4_sys_baseline18_ghw72"),
                 sys_dir="error_model_comparison_18_4_4_sys_baseline18_ghw72",
                 baseline="error_model_comparison_18_4_4"):
        self.DEV, self.RET = run_dir(dev), run_dir(retired)
        self.SYS, self.BASE = run_dir(sys_dir), run_dir(baseline)

    @staticmethod
    def _spec(root, task):
        j = json.loads((root / f"{task}.json").read_text(encoding="utf-8"))["result"]
        keep = set(FailureSpectrum.__dataclass_fields__)
        return FailureSpectrum(**{k: v for k, v in j["spectrum"].items() if k in keep})

    def load(self):
        self.dev72 = {m: self._spec(self.DEV, f"tech1_72__{slug(m)}") for m in DEV_CHANNELS72}
        self.ret72 = {m: self._spec(self.RET, f"tech1_72__{slug(m)}") for m in DEV_CHANNELS72}
        self.full_ghw = self._spec(self.SYS, "tech1_72__full_symmetric")
        self.full_base = self._spec(self.BASE, "tech1_72__full_symmetric")
        n_tu = sum(1 for m in DEV_CHANNELS72
                   if "onset_topup" in json.loads(
                       (self.DEV / f"tech1_72__{slug(m)}.json").read_text(encoding="utf-8")
                   )["result"]["spectrum"])
        print(f"loaded 5 channels x (device, specialist) + full-sym anchors; "
              f"{n_tu}/5 device channels have top-up bins so far")

    # --- §1 channels: device vs specialist ---------------------------------------

    def fig_channels(self):
        fig, axes = plt.subplots(1, 5, figsize=(16, 3.4), sharey=True)
        for ax, m in zip(axes, DEV_CHANNELS72):
            for spec, color, label, mk in [(self.ret72[m], "0.55", "specialist", "o"),
                                           (self.dev72[m], COLORS[m], "device", "x")]:
                W = np.asarray(spec.weights); F = np.asarray(spec.failures, float)
                T = np.asarray(spec.trials, float)
                meas = F > 0
                f = F[meas] / T[meas]
                se = np.sqrt(f * (1 - f) / T[meas])
                ax.errorbar(W[meas], f, 1.96 * se, fmt=mk, color=color, ms=5,
                            lw=1, capsize=2, label=label)
                z = ~meas & (T > 0)
                ax.plot(W[z], 1.0 / (2 * T[z]), marker="v", ls="none", ms=4,
                        mfc="none", mec=color, alpha=0.6)
            ax.set_yscale("log"); ax.set_title(m, fontsize=10)
            ax.set_xlabel("fault weight w"); ax.grid(alpha=0.3, which="both")
        axes[0].set_ylabel("f(w)")
        axes[0].legend(fontsize=8, loc="upper left")
        fig.suptitle("[[72,4,8]] channel spectra — specialist (retired) vs device decoder "
                     "(hollow ▽ = zero-failure bin, 1/(2T) bound)", y=1.04)
        plt.tight_layout(); plt.show()

    def ratio_table(self):
        print(f"{'channel':12s} {'w':>3} {'device':>14} {'specialist':>14} "
              f"{'ratio':>7} {'z':>6}")
        for m in DEV_CHANNELS72:
            d = {w: (f, t) for w, f, t in
                 zip(self.dev72[m].weights, self.dev72[m].failures, self.dev72[m].trials)}
            r = {w: (f, t) for w, f, t in
                 zip(self.ret72[m].weights, self.ret72[m].failures, self.ret72[m].trials)}
            shown = 0
            for w in sorted(set(d) & set(r)):
                (fd, td), (fr, tr) = d[w], r[w]
                if fd == 0 and fr == 0:
                    continue
                rd, rr = fd / td, fr / tr
                var = (max(fd, 1) / td**2) + (max(fr, 1) / tr**2)
                z = (rd - rr) / np.sqrt(var)
                ratio = f"{rd/rr:7.2f}" if fd and fr else "   n/a "
                print(f"{m:12s} {w:3d} {fd:6d}/{td:<8.0f} {fr:6d}/{tr:<8.0f}"
                      f"{ratio} {z:6.1f}")
                shown += 1
            if not shown:
                print(f"{m:12s}   no measured bins on either side yet")
        print("\nz: normal approx on the rate difference; |z|>2 is a real priors effect.")

    # --- §2 full-symmetric anchors (convention-invariant) ------------------------

    def anchor_table(self, p_star=5e-4, rounds72=7):
        print(f"full-symmetric [[72,4,8]] anchors at p* = {p_star} (convention-invariant):")
        out = {}
        for tag, spec in [("baseline", self.full_base), ("ghw", self.full_ghw)]:
            v = reweight_spectrum(spec, [p_star])
            L, se = float(v.P_logical[0]), float(v.P_logical_se[0])
            up = FailureSpectrum(weights=spec.weights, trials=spec.trials,
                                 failures=[f if f > 0 else min(3, t)
                                           for f, t in zip(spec.failures, spec.trials)],
                                 n_expanded=spec.n_expanded, q_base=spec.q_base,
                                 p_ref=spec.p_ref)
            head = float(reweight_spectrum(up, [p_star]).P_logical[0]) - L
            out[tag] = (L, se, head)
            print(f"  {tag:9s}: LER = {L:.3e} ± {se:.1e}   zero-bin headroom +{head/L*100:.0f}%")
        (Lb, _, _), (Lg, _, hg) = out["baseline"], out["ghw"]
        print(f"  decoder improvement: {Lb/Lg:.1f}x  "
              f"(floor {Lb/(Lg+hg):.1f}x pricing every ghw zero bin at 3/T)")


# ---------------------------------------------------------------------------
# Decoder generations: baseline -> ghw -> ghw_deep on the same models
# ---------------------------------------------------------------------------
GEN_DIRS = [
    ("baseline", "error_model_comparison_18_4_4", "0.45"),
    ("ghw", "error_model_comparison_18_4_4_device_baseline18_ghw72", "#2c7fb8"),
    ("ghw_deep", "error_model_comparison_18_4_4_device_baseline18_ghw_deep72", "#c51b8a"),
]


def _gen_spec(run_name, task):
    p = run_dir(run_name) / f"{task}.json"
    if not p.exists():
        return None
    s = json.loads(p.read_text(encoding="utf-8"))["result"]["spectrum"]
    return {int(w): (int(f), int(t)) for w, f, t in
            zip(s["weights"], s["failures"], s["trials"])}


def fig_decoder_generations(models=("full_symmetric", "CZ_only", "meas_only",
                                    "prep_only", "gate_idle", "meas_idle"),
                            w_max=10, w0=4, min_trials=100_000):
    """f(w) in the SUB-ONSET band for each decoder generation, same models and convention.

    Only bins with >= `min_trials` are drawn, so generation-depth bins (10k caps) cannot
    masquerade as measurements of a 1e-6-class rate. Filled markers are measured rates
    with 95% binomial bars; open triangles are zero-failure bins plotted at their
    rule-of-three upper bound 3/T. The shaded band is w < w0 = ceil(D/2): below the
    perfect-decoder onset, so anything there is decoder miscorrection, not a code limit.
    """
    n = len(models)
    ncol = 3
    nrow = int(np.ceil(n / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(4.6 * ncol, 3.7 * nrow),
                             sharex=True, sharey=True)
    axes = np.atleast_1d(axes).ravel()
    for ax, model in zip(axes, models):
        ax.axvspan(1.5, w0 - 0.5, color="#f2e6c7", alpha=0.55, zorder=0)
        for label, run_name, colour in GEN_DIRS:
            d = _gen_spec(run_name, f"tech1_72__{model}")
            if not d:
                continue
            ws, rs, los, his, bw, bv = [], [], [], [], [], []
            for w in sorted(d):
                if w > w_max:
                    continue
                f, t = d[w]
                if t < min_trials:
                    continue
                if f == 0:
                    bw.append(w); bv.append(3.0 / t)
                    continue
                r = f / t
                se = 1.96 * np.sqrt(r * (1 - r) / t)
                ws.append(w); rs.append(r)
                los.append(min(se, r * 0.999)); his.append(se)
            if ws:
                ax.errorbar(ws, rs, yerr=[los, his], fmt="o-", ms=4.5, lw=1.3,
                            capsize=2, color=colour, label=label, zorder=3)
            if bw:
                ax.plot(bw, bv, "v", ms=6, mfc="none", mec=colour, mew=1.4, zorder=3)
        ax.axvline(w0, color="k", ls="--", lw=0.9)
        ax.set_yscale("log")
        ax.set_title(model.replace("_", " "), fontsize=10)
        ax.grid(alpha=0.3, which="both")
        ax.set_xticks(range(2, w_max + 1))
    for ax in axes[n:]:
        ax.set_visible(False)
    for i, ax in enumerate(axes[:n]):
        if i % ncol == 0:
            ax.set_ylabel("f(w)")
        if i >= n - ncol:
            ax.set_xlabel("fault weight w")
    axes[0].legend(fontsize=8, loc="lower right")
    fig.suptitle("[[72,4,8]] sub-onset floor by decoder generation — device calibration, "
                 f"3e6-shot bins (shaded: w < w0={w0}, pure decoder miscorrection; "
                 "open ▽ = zero-failure bin at 3/T)", fontsize=11, y=1.0)
    plt.tight_layout()
    plt.show()


def decoder_generations_table(models=("full_symmetric", "CZ_only", "meas_only",
                                      "prep_only", "gate_idle", "meas_idle"),
                              ws=(2, 3, 4, 5), min_trials=100_000):
    """The same content as a table — every number quotable, with its denominator."""
    hdr = "  ".join(f"{'w=' + str(w):>16s}" for w in ws)
    for label, run_name, _ in GEN_DIRS:
        print(f"\n=== {label} ===")
        print(f"{'model':16s} {hdr}")
        for model in models:
            d = _gen_spec(run_name, f"tech1_72__{model}")
            if not d:
                continue
            cells = []
            for w in ws:
                v = d.get(w)
                if v is None or v[1] < min_trials:
                    cells.append("       —        ")
                else:
                    cells.append(f"{v[0]:>4d}/{v[1]:<11,}")
            print(f"{model:16s} " + "  ".join(cells))
    print(f"\n(bins with < {min_trials:,} trials shown as — : generation depth cannot "
          f"resolve a 1e-6-class rate)")


def _gen_fullspec(run_name, task):
    """FailureSpectrum for a task in a campaign cache (None if absent)."""
    p = run_dir(run_name) / f"{task}.json"
    if not p.exists():
        return None
    s = json.loads(p.read_text(encoding="utf-8"))["result"]["spectrum"]
    keep = set(FailureSpectrum.__dataclass_fields__)
    return FailureSpectrum(**{k: v for k, v in s.items() if k in keep})


def fig_generations_spectra(model="full_symmetric", p_grid=None):
    """Full IS failure spectrum f(w) and the reweighted LER(p) it implies, per decoder.

    Left: every measured bin, so the sub-onset band and the shoulder are visible in one
    picture. Right: the same spectra reweighted to a range of physical error rates —
    this is the quantity the campaign actually quotes, and it shows what the sub-onset
    improvement is worth in LER terms.
    """
    if p_grid is None:
        p_grid = np.geomspace(1e-4, 1e-2, 40)
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(13, 4.8))
    for label, run_name, colour in GEN_DIRS:
        spec = _gen_fullspec(run_name, f"tech1_72__{model}")
        if spec is None:
            continue
        W = np.asarray(spec.weights); F = np.asarray(spec.failures, float)
        T = np.asarray(spec.trials, float)
        hit = F > 0
        r = F[hit] / T[hit]
        se = 1.96 * np.sqrt(r * (1 - r) / T[hit])
        axL.errorbar(W[hit], r, yerr=[np.minimum(se, r * 0.999), se], fmt="o-", ms=3.5,
                     lw=1.2, capsize=1.5, color=colour, label=label)
        z = (~hit) & (T > 0)
        if z.any():
            axL.plot(W[z], 3.0 / T[z], "v", ms=5, mfc="none", mec=colour, mew=1.2)
        # The reweighted LER counts only MEASURED failures, so a zero-failure bin
        # contributes exactly zero -> the curve is optimistic wherever the sampling could
        # not resolve the rate. Draw the honest band: the solid line assumes those bins
        # are truly empty, the upper edge prices each at its rule-of-three bound 3/T.
        filled = fill_spectrum(spec)
        L = [float(reweight_spectrum(filled, [p]).P_logical[0]) for p in p_grid]
        up = FailureSpectrum(weights=filled.weights, trials=filled.trials,
                             failures=[f if f > 0 else min(3, t)
                                       for f, t in zip(filled.failures, filled.trials)],
                             n_expanded=filled.n_expanded, q_base=filled.q_base,
                             p_ref=filled.p_ref)
        L_hi = [float(reweight_spectrum(up, [p]).P_logical[0]) for p in p_grid]
        axR.plot(p_grid, L, "-", lw=2, color=colour, label=label)
        axR.fill_between(p_grid, L, L_hi, color=colour, alpha=0.18, lw=0)
    for ax in (axL, axR):
        ax.set_yscale("log"); ax.grid(alpha=0.3, which="both")
    axL.set_xscale("log")
    axL.set_xlabel("fault weight w"); axL.set_ylabel("f(w)")
    axL.set_title(f"IS failure spectrum — {model.replace('_', ' ')}", fontsize=10)
    axL.legend(fontsize=8)
    axR.set_xscale("log")
    axR.axvline(5e-4, color="0.6", ls=":", lw=1)
    axR.text(5.3e-4, axR.get_ylim()[0] * 3, "p*", color="0.4", fontsize=8)
    axR.set_xlabel("physical error rate p"); axR.set_ylabel(r"$P_{\rm logical}$ (reweighted)")
    axR.set_title("reweighted LER — solid: empty bins counted as zero; "
                  "shaded: each priced at its 3/T bound", fontsize=10)
    axR.legend(fontsize=8)
    plt.tight_layout(); plt.show()


def generations_lambda(p_star=5e-4, rounds18=None, rounds72=None,
                       model18="tech1__full_symmetric", model72="tech1_72__full_symmetric"):
    """Λ = ε18/ε72 per decoder generation, with the zero-bin truncation band.

    The 18-code runs the baseline decoder in every campaign (ghw's wide gamma interval is
    measured-broken there), so Λ moves only through the 72-code — i.e. this is exactly the
    system-level Λ the campaign quotes, and the improvement is the decoder's.
    """
    # Round counts come from the campaign manifest, never hardcoded: epsilon is PER ROUND,
    # so a wrong count silently rescales every Lambda. This campaign runs 2 rounds on the
    # [[18,4,4]] code and 4 on the [[72,4,8]].
    if rounds18 is None or rounds72 is None:
        man = json.loads((run_dir("error_model_comparison_18_4_4") /
                          "config__manifest.json").read_text(encoding="utf-8"))["config"]
        rounds18 = rounds18 if rounds18 is not None else man["rounds"]
        rounds72 = rounds72 if rounds72 is not None else man["rounds72"]
    s18 = _gen_fullspec("error_model_comparison_18_4_4", model18)
    v18 = reweight_spectrum(s18, [p_star])
    e18 = float(per_round(np.asarray([float(v18.P_logical[0])]), rounds18)[0])
    print(f"Λ = ε18 / ε72  at p* = {p_star}   (18-code = baseline decoder throughout; "
          f"{rounds18} rounds on the 18-code, {rounds72} on the 72-code)")
    print(f"  ε18 = {e18:.3e}\n")
    print(f"{'72-code decoder':14s} {'ε72':>12s} {'Λ':>10s} {'Λ floor':>10s}   (floor prices"
          f" every zero bin at 3/T)")
    for label, run_name, _ in GEN_DIRS:
        s72 = _gen_fullspec(run_name, model72)
        if s72 is None:
            continue
        filled = fill_spectrum(s72)
        L = float(reweight_spectrum(filled, [p_star]).P_logical[0])
        up = FailureSpectrum(weights=filled.weights, trials=filled.trials,
                             failures=[f if f > 0 else min(3, t)
                                       for f, t in zip(filled.failures, filled.trials)],
                             n_expanded=filled.n_expanded, q_base=filled.q_base,
                             p_ref=filled.p_ref)
        L_hi = float(reweight_spectrum(up, [p_star]).P_logical[0])
        e72 = float(per_round(np.asarray([L]), rounds72)[0])
        e72_hi = float(per_round(np.asarray([L_hi]), rounds72)[0])
        print(f"{label:14s} {e72:12.3e} {e18/e72:10.0f} {e18/e72_hi:10.0f}")
    print("\nΛ is a RANGE, not a point: unmeasured (zero-failure) low-weight bins could "
          "each sit\nanywhere below their 3/T bound, and the floor column prices them all "
          "at that bound.")


def fig_weight_contributions(model="full_symmetric", p_lo=1e-5, p_hi=5e-3, w_max=20):
    """Which fault weights carry the logical error rate, as a function of p.

    LER(p) = sum_w P(W=w | p) f(w), so each weight's share is
    C(N,w) q^w (1-q)^(N-w) f(w) normalised over w. This is the picture behind the LER
    slope: the lightest weight with a NON-ZERO measured f(w) dominates as p falls, so a
    decoder with a sub-onset floor at w=3 scales as p^3 while a clean one recovers p^4.

    Colour is each weight's fractional contribution at that p; the white line is the
    contribution-weighted mean weight; the dashed line marks the perfect-decoder onset.
    """
    from scipy.stats import binom as _binom
    pg = np.geomspace(p_lo, p_hi, 90)
    fig, axes = plt.subplots(1, len(GEN_DIRS), figsize=(5.0 * len(GEN_DIRS), 4.2),
                             sharey=True)
    axes = np.atleast_1d(axes)
    for ax, (label, run_name, _) in zip(axes, GEN_DIRS):
        spec = _gen_fullspec(run_name, f"tech1_72__{model}")
        if spec is None:
            ax.set_visible(False)
            continue
        s = fill_spectrum(spec)
        W = np.asarray(s.weights); F = np.asarray(s.failures, float)
        T = np.asarray(s.trials, float)
        keep = W <= w_max
        W, f_w = W[keep], np.divide(F[keep], T[keep], out=np.zeros(keep.sum()),
                                    where=T[keep] > 0)
        M = np.zeros((len(W), len(pg)))
        for j, p in enumerate(pg):
            q = s.q_base * (p / s.p_ref)
            contrib = _binom.pmf(W, s.n_expanded, q) * f_w
            tot = contrib.sum()
            M[:, j] = contrib / tot if tot > 0 else 0.0
        im = ax.pcolormesh(pg, W, M, shading="nearest", cmap="viridis",
                           vmin=0, vmax=max(M.max(), 1e-9))
        mean_w = (M * W[:, None]).sum(axis=0)
        ax.plot(pg, mean_w, "-", color="white", lw=2)
        w_lo = W[f_w > 0].min() if (f_w > 0).any() else None
        if w_lo is not None:
            ax.axhline(w_lo, color="crimson", ls="-", lw=1.4)
            ax.text(pg[2], w_lo + 0.4, f"lightest measured failure: w={w_lo}",
                    color="crimson", fontsize=8)
        ax.axhline(4, color="w", ls="--", lw=1.0, alpha=0.8)
        ax.set_xscale("log")
        ax.set_xlabel("physical error rate p")
        ax.set_title(label, fontsize=10)
    axes[0].set_ylabel("fault weight w")
    fig.colorbar(im, ax=list(axes), label="share of LER at that p", pad=0.02)
    fig.suptitle(f"[[72,4,8]] {model.replace('_', ' ')} — which fault weights carry the "
                 "logical error rate\n(white: mean contributing weight; dashed: perfect-"
                 "decoder onset w0=4; red: lightest weight this decoder actually fails)",
                 fontsize=11, y=1.04)
    plt.show()


def ler_slope_table(model="full_symmetric",
                    ranges=((1e-5, 1e-4), (1e-4, 5e-4), (2e-4, 1e-3), (1e-3, 5e-3))):
    """Local log-log slope d log LER / d log p — i.e. the effective exponent LER ~ p^k.

    Asymptotically k -> the lightest fault weight the decoder fails, so a sub-onset floor
    does not merely add an offset: it DEGRADES THE EXPONENT, and the penalty grows without
    limit as p falls.
    """
    hdr = "  ".join(f"{f'{a:.0e}-{b:.0e}':>12s}" for a, b in ranges)
    print(f"{'decoder':10s} {hdr}   lightest failing w")
    for label, run_name, _ in GEN_DIRS:
        spec = _gen_fullspec(run_name, f"tech1_72__{model}")
        if spec is None:
            continue
        s = fill_spectrum(spec)
        cells = []
        for a, b in ranges:
            pg = np.geomspace(a, b, 6)
            L = np.array([float(reweight_spectrum(s, [p]).P_logical[0]) for p in pg])
            cells.append(f"{np.polyfit(np.log(pg), np.log(L), 1)[0]:12.2f}")
        w_lo = min(w for w, f in zip(s.weights, s.failures) if f > 0)
        print(f"{label:10s} " + "  ".join(cells) + f"   w = {w_lo}")
    print("\nThe leftmost column is closest to asymptotic. A decoder failing at w=3 scales")
    print("as p^3; one clean to the true onset recovers p^4 — the code's own scaling.")


def _weight_map_panel(ax, spec, p_grid, w_max, onset):
    """Shared drawing for the weight-vs-p contribution maps. Returns the mesh handle."""
    from scipy.stats import binom as _binom
    s = fill_spectrum(spec)
    W = np.asarray(s.weights); F = np.asarray(s.failures, float); T = np.asarray(s.trials, float)
    keep = (W <= w_max) & (T > 0)
    W = W[keep]
    f_w = F[keep] / T[keep]
    M = np.zeros((len(W), len(p_grid)))
    for j, p in enumerate(p_grid):
        q = s.q_base * (p / s.p_ref)
        c = _binom.pmf(W, s.n_expanded, q) * f_w
        tot = c.sum()
        M[:, j] = c / tot if tot > 0 else 0.0
    im = ax.pcolormesh(p_grid, W, M, shading="nearest", cmap="viridis", vmin=0)
    ax.plot(p_grid, (M * W[:, None]).sum(axis=0), "-", color="white", lw=1.8)
    if (f_w > 0).any():
        w_lo = W[f_w > 0].min()
        ax.axhline(w_lo, color="crimson", lw=1.3)
        ax.text(p_grid[2], w_lo + 0.5, f"w={w_lo}", color="crimson", fontsize=7)
    ax.axhline(onset, color="w", ls="--", lw=0.9, alpha=0.85)
    ax.set_xscale("log")
    return im


def _weight_map(report, code="72", models=None, p_lo=1e-5, p_hi=5e-3, w_max=20):
    """Companion to fig_spectrum_grid: WHICH fault weights carry the LER, versus p.

    The spectrum grid answers "how often does weight w fail?"; this answers "which w
    actually matters at a given physical error rate?" — the product of that failure
    fraction with the binomial weight of w at p, normalised. As p falls, the mass
    collapses onto the lightest weight with a NON-ZERO measured f(w), which is a property
    of the decoder, not of the code: it sets the exponent of LER ~ p^k.
    """
    models = list(models or report.MODELS)
    prefix = "tech1_72__" if code == "72" else "tech1__"
    onset = (report.load(f"tech2_72__full_symmetric" if code == "72"
                         else "tech2__full_symmetric")["D"] + 1) // 2
    p_grid = np.geomspace(p_lo, p_hi, 90)
    ncol = 3
    nrow = int(np.ceil(len(models) / ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5.3 * ncol, 3.6 * nrow),
                             sharex=True, sharey=True)
    axes = np.atleast_1d(axes).ravel()
    im = None
    for ax, m in zip(axes, models):
        try:
            r = report.load(f"{prefix}{slug(m)}")
        except FileNotFoundError:
            ax.set_visible(False)
            continue
        im = _weight_map_panel(ax, report.spectrum_of(r), p_grid, w_max, onset)
        ax.set_title(m, fontsize=10)
    for ax in axes[len(models):]:
        ax.set_visible(False)
    for i, ax in enumerate(axes[:len(models)]):
        if i % ncol == 0:
            ax.set_ylabel("fault weight w")
        if i >= len(models) - ncol:
            ax.set_xlabel("physical error rate p")
    if im is not None:
        fig.colorbar(im, ax=list(axes), label="share of LER at that p", pad=0.02)
    label = "[[72,4,8]]" if code == "72" else "[[18,4,4]]"
    fig.suptitle(f"{label} — which fault weights carry the logical error rate\n"
                 f"(white: mean contributing weight; dashed: perfect-decoder onset "
                 f"w₀={onset}; red: lightest weight this decoder actually fails)",
                 fontsize=11, y=1.02)
    plt.show()


Report.fig_weight_map = _weight_map
